version: '3.8'

services: 
  postgres: 
    image: postgres:alpine
    container_name: ClickCut._database
    restart: unless-stopped

    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=clickcut

    ports:
      - "5455:5432"
      
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local